version: '3.8'

services:
  nba_db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: container-postgresdb
    ports:
      - "5432:5432"
    networks: 
      - postgresnetwork
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - nba_db
    links:
      - nba_db:pg_container
    networks: 
      - postgresnetwork

networks:
  postgresnetwork:
    driver: bridge

